// Sub Gourmet menu, transcribed from the restaurant's own menu boards published
// at maison.hr (/sgmenu/ and /breakfast/), checked 2026-08-31. Prices in euros.
// Keep this file in step with the printed menu.
const MENU_DATA = [
  {
    id: 'breakfast',
    hr: 'Doručak',
    en: 'Breakfast',
    hours: '09:00 – 11:30 · Monday to Sunday',
    hoursHr: '09:00 – 11:30 · Ponedjeljak do nedjelje',
    items: [
      { hr: 'Slavonski doručak', en: 'Slavonic Breakfast', desc: 'Two sunny side up eggs, sausage, salad, mustard', descHr: 'Dva jaja na oko, kobasica, panceta, salata, senf', price: '11.90' },
      { hr: 'Omlet', en: 'Omelette', desc: 'Three eggs, salad · Extras 0.90 each: ham, cheese, mushroom, bacon, vegetables', descHr: 'Tri jaja, salata · Dodaci 0,90 svaki: šunka, sir, gljive, panceta, povrće', price: '7.90' },
      { hr: 'Sendvić u lepinji', en: 'Sandwich in a Bun', desc: 'Homemade bun, cream, cheese, ham, tomato, green salad', descHr: 'Domaća lepinja, vrhnje, sir, šunka, rajčica, zelena salata', price: '11.90' },
      { hr: 'Omlet u tortilji', en: 'Omelette in Tortilla', desc: 'Tortilla, two eggs, tomato, cheese, salad', descHr: 'Tortilja, dva jaja, rajčica, sir, salata', price: '8.90' },
      { hr: 'Palačinke', en: 'Pancakes', desc: 'Two pancakes with marmalade or chocolate', descHr: 'Dvije palačinke s marmeladom ili čokoladom', price: '5.20' },
      { hr: 'Dubrovački doručak', en: 'Dubrovnik Breakfast', desc: 'Homemade fritters, prosciutto, cheese, cream, tomato, olives, salad', descHr: 'Domaći uštipci, pršut, sir, kiselo vrhnje, rajčica, masline, salata', price: '12.90' },
      { hr: 'Fitness doručak', en: 'Fitness Breakfast', desc: 'Oat flakes, chia seeds, cream, strawberry puree', descHr: 'Zobene pahuljice, chia sjemenke, mileram, pire od jagode', price: '9.90' },
      { hr: 'Sub Gourmet doručak', en: 'Sub Gourmet Breakfast', desc: 'Two poached eggs, toast, mozzarella, salad', descHr: 'Dva poširana jaja, tost, mozzarella, salata', price: '12.90', signature: true },
      { hr: 'Kajgana', en: 'Scrambled Eggs', desc: 'Three eggs, cheese, cherry tomatoes, salad', descHr: 'Tri jaja, sir, cherry rajčica, salata', price: '9.90' },
    ],
  },
  {
    id: 'appetizers',
    hr: 'Predjela',
    en: 'Appetizers',
    note: 'To start.',
    noteHr: 'Za početak.',
    items: [
      { hr: 'Proljetne rolice', en: 'Spring Rolls', desc: 'Vegetables, sweet chilli sauce', descHr: 'Povrće, umak sweet chilli', price: '8.40' },
      { hr: 'Proljetne rolice s piletinom i povrćem', en: 'Spring Rolls with Chicken and Vegetables', desc: 'Pieces of chicken, vegetables, sweet chilli sauce', descHr: 'Komadići piletine, povrće, umak sweet chilli', price: '9.60' },
      { hr: 'Repovi kozica', en: 'Shrimp Tails', desc: 'Sweet chilli sauce', descHr: 'Umak sweet chilli', price: '10.90' },
    ],
  },
  {
    id: 'soups',
    hr: 'Juhe',
    en: 'Soups',
    note: 'From the pot.',
    noteHr: 'Iz lonca.',
    items: [
      { hr: 'Domaća goveđa juha', en: 'Homemade Beef Soup', desc: 'Carrots, celery, noodles', descHr: 'Mrkva, celer, rezanci', price: '5.50' },
      { hr: 'Juha od rajčice', en: 'Tomato Soup', desc: 'Fresh tomatoes, peeled tomatoes, carrots, onions, peppers', descHr: 'Svježe rajčice, pelata, mrkva, luk, paprika', price: '6.00' },
      { hr: 'Krem juha od tikve', en: 'Cream Pumpkin Soup', desc: 'Pumpkin, onions, carrot', descHr: 'Tikva, luk, mrkva', price: '7.00' },
    ],
  },
  {
    id: 'salads',
    hr: 'Salate',
    en: 'Salads',
    note: 'Fresh from the garden.',
    noteHr: 'Svježe iz vrta.',
    items: [
      { hr: 'Sezonska salata', en: 'Season Salad', price: '7.80' },
      { hr: 'Grčka salata', en: 'Greek Salad', desc: 'Tomatoes, peppers, cucumbers, feta cheese, olives, onion', descHr: 'Rajčica, paprika, krastavci, feta sir, masline, luk', price: '12.30' },
      { hr: 'Cezar salata s piletinom', en: 'Caesar Salad with Chicken', desc: 'Chicken, green salad, arugula, tomato, cucumber, cherry tomato, croutons', descHr: 'Piletina, zelena salata, rikula, rajčica, krastavci, cherry rajčica, krutoni', price: '13.90' },
      { hr: 'Tuna salata', en: 'Tuna Salad', desc: 'Tuna, lettuce, arugula, cucumber, tomato, onion, corn, capers, olives, reduced vinegar', descHr: 'Tuna, zelena salata, rikula, krastavac, rajčica, luk, kukuruz, kapari, maslina, aceto', price: '16.40' },
    ],
  },
  {
    id: 'pasta',
    hr: 'Tjestenine',
    en: 'Pasta',
    note: 'Made to order.',
    noteHr: 'Pripremljeno po narudžbi.',
    items: [
      { hr: 'Pasta Napolitana', en: 'Napolitan Pasta', desc: 'Tomato sauce', descHr: 'Umak od rajčice', price: '13.60' },
      { hr: 'Spaghetti Carbonara', en: 'Spaghetti Carbonara', desc: 'Bacon, ham', descHr: 'Panceta, šunka', price: '14.40' },
      { hr: 'Spaghetti Bolognese', en: 'Spaghetti Bolognese', desc: 'Beef, tomato sauce', descHr: 'Junetina, pelata', price: '14.60' },
      { hr: 'Njoke s kozicama i kaduljom', en: 'Gnocchi with Prawns and Sage', desc: 'Homemade prawns, peeled tomato', descHr: 'Domaće kozice, pelata', price: '16.60' },
      { hr: 'Tortellini s pršutom i gljivama', en: 'Tortellini with Prosciutto and Mushrooms', desc: 'Prosciutto, mushrooms', descHr: 'Pršut, gljive', price: '15.30' },
      { hr: 'Tagliatelle s umakom od tartufa', en: 'Tagliatelle with Truffle Sauce', desc: 'Truffle sauce, cream, cheese', descHr: 'Umak od tartufa, vrhnje, sir', price: '16.30' },
      { hr: 'Tagliatelle s kozicama u umaku od tartufa', en: 'Tagliatelle with Shrimps in Truffle Sauce', desc: 'Shrimps, tomato, truffle sauce, cream', descHr: 'Kozice, rajčica, umak od tartufa, vrhnje', price: '18.30' },
    ],
  },
  {
    id: 'mains',
    hr: 'Glavna jela',
    en: 'Main Courses',
    note: 'From the grill and the pan.',
    noteHr: 'S roštilja i iz tave.',
    items: [
      { hr: 'Piletina u umaku od gljiva', en: 'Chicken in Mushroom Sauce', desc: 'Chicken, mushrooms, mashed potatoes or French fries', descHr: 'Piletina, gljive, pire krumpir ili pomfrit', price: '18.30' },
      { hr: 'Pileći file sa žara', en: 'Grilled Chicken Fillet', desc: 'Chicken, French fries or grilled vegetables', descHr: 'Piletina, pomfrit ili grill povrće', price: '17.10' },
      { hr: 'Ćevapi + lepinja', en: 'Ćevapi + Flat Bread', desc: 'Ćevapi 8 pcs., flat bread, onion, ajvar', descHr: 'Ćevapi 8 kom., lepinja, luk, ajvar', price: '16.90' },
      { hr: 'Lignje sa žara', en: 'Grilled Squid', desc: 'Squid, grilled vegetables or French fries', descHr: 'Lignje, grill povrće ili pomfrit', price: '20.60' },
      { hr: 'Fish and Chips', en: 'Fish and Chips', desc: 'Hake fish fillet, tartar sauce, French fries', descHr: 'Filet oslića, tartar umak, pomfrit', price: '17.60' },
    ],
  },
  {
    id: 'pizza',
    hr: 'Pizza',
    en: 'Pizza',
    note: 'Stone baked.',
    noteHr: 'Pečena na kamenu.',
    items: [
      { hr: 'Margarita', en: 'Margarita', desc: 'Tomato sauce, mozzarella cheese, oregano, olive, basil, olive oil', descHr: 'Pelata, mozzarella sir, origano, maslina, bosiljak, maslinovo ulje', price: '13.90' },
      { hr: 'Funghi', en: 'Funghi', desc: 'Tomato sauce, mozzarella cheese, mushrooms, oregano, olive', descHr: 'Pelata, mozzarella sir, gljive, origano, maslina', price: '14.30' },
      { hr: 'Romana', en: 'Romana', desc: 'Tomato sauce, mozzarella cheese, ham, bacon, oregano, olive', descHr: 'Pelata, mozzarella sir, šunka, panceta, origano, maslina', price: '14.60' },
      { hr: 'Capricciosa', en: 'Capricciosa', desc: 'Tomato sauce, mozzarella cheese, ham, mushrooms, oregano, olive', descHr: 'Pelata, mozzarella sir, šunka, gljive, origano, maslina', price: '14.90' },
      { hr: 'Quattro Formaggi', en: 'Quattro Formaggi', desc: 'Tomato sauce, four types of cheese, oregano, olive', descHr: 'Pelata, četiri vrste sira, origano, maslina', price: '16.30' },
      { hr: 'Gurmanska', en: 'Gourmet', desc: 'Tomato sauce, mozzarella cheese, prosciutto, ham, cherry tomato, egg, oregano, olive', descHr: 'Pelata, mozzarella sir, pršut, šunka, cherry rajčica, jaje, origano, maslina', price: '15.90' },
      { hr: 'Tuna', en: 'Tuna', desc: 'Tomato sauce, mozzarella cheese, tuna, onion, capers, oregano, olive', descHr: 'Pelata, mozzarella sir, tuna, luk, kapari, origano, maslina', price: '15.90' },
      { hr: 'Piccante', en: 'Piccante', desc: 'Tomato sauce, mozzarella cheese, ham, bacon, kulen, hot peppers, oregano, olive', descHr: 'Pelata, mozzarella sir, šunka, panceta, kulen, ljuti feferoni, origano, maslina', price: '16.80' },
      { hr: 'Sub Gourmet', en: 'Sub Gourmet', desc: 'Tomato sauce, mozzarella cheese, prosciutto, arugula, grana padano, cherry tomatoes, reduced aceto, oregano, olive', descHr: 'Pelata, mozzarella sir, pršut, rikula, grana padano, cherry rajčica, reducirani aceto, origano, maslina', price: '18.20', signature: true },
      { hr: 'Slavonska', en: 'Slavonska', desc: 'Tomato sauce, mozzarella cheese, ham, mushrooms, bacon, kulen, onion, oregano, olive', descHr: 'Pelata, mozzarella sir, šunka, gljive, panceta, kulen, luk, origano, maslina', price: '16.30' },
      { hr: 'Vegetariana', en: 'Vegetariana', desc: 'Tomato sauce, mozzarella cheese, tomatoes, zucchini, peppers, onion, corn, oregano, olive', descHr: 'Pelata, mozzarella sir, rajčica, tikvice, paprika, luk, kukuruz, origano, maslina', price: '16.30' },
      { hr: 'Calzone', en: 'Calzone', desc: 'Tomato sauce, mozzarella cheese, ham, mushrooms, sour cream, oregano, olive', descHr: 'Pelata, mozzarella sir, šunka, gljive, kiselo vrhnje, origano, maslina', price: '14.90' },
    ],
  },
  {
    id: 'burgers',
    hr: 'Burgeri',
    en: 'Burgers',
    note: 'On a brioche bun.',
    noteHr: 'U brioche pecivu.',
    items: [
      { hr: 'Klasik', en: 'Classic', desc: 'Brioche bun, 150g 100% beef, lettuce, white sauce, onion, tomato, BBQ sauce', descHr: 'Brioche pecivo, 150g 100% junetina, zelena salata, bijeli umak, luk, rajčica, BBQ umak', price: '12.70' },
      { hr: 'Cheeseburger', en: 'Cheeseburger', desc: 'Brioche bun, 150g 100% beef, cheese, lettuce, white sauce, onion, tomato, BBQ', descHr: 'Brioche pecivo, 150g 100% junetina, sir, zelena salata, bijeli umak, luk, rajčica, BBQ', price: '13.90' },
      { hr: 'Duplo', en: 'Double', desc: 'Brioche bun, 300g 100% beef, lettuce, slightly pickled cucumbers, white sauce, tomato, BBQ', descHr: 'Brioche pecivo, 300g 100% junetina, zelena salata, blago kiseli krastavci, bijeli umak, rajčica, BBQ umak', price: '19.20' },
      { hr: 'Spicy', en: 'Spicy', desc: 'Brioche bun, 150g 100% beef, pickled jalapeno peppers, lettuce, tomatoes, caramelized onion, white sauce, spicy sauce', descHr: 'Brioche pecivo, 150g 100% junetina, ukiseljene jalapeno papričice, zelena salata, rajčica, karamelizirani luk, bijeli umak, spicy umak', price: '14.10' },
      { hr: 'Pileći burger', en: 'Chicken Burger', desc: 'Brioche bun, 150g 100% chicken, lettuce, tomato, Thousand Island sauce', descHr: 'Brioche pecivo, 150g 100% piletina, zelena salata, rajčica, umak Thousand Island', price: '16.10' },
      { hr: 'Vegeeee', en: 'Vegeeee', desc: 'Brioche bun, veggie burger, lettuce, tomato, onion, caramelized onion, BBQ sauce', descHr: 'Brioche pecivo, vege pljeskavica, zelena salata, rajčica, luk, karamelizirani luk, BBQ', price: '16.10' },
      { hr: 'Našburger', en: 'Našburger', desc: 'Brioche bun, 150g 100% beef, lettuce, white cabbage, egg, caramelized onion, white sauce, onion', descHr: 'Brioche pecivo, 150g 100% junetina, zelena salata, jaje, bijeli kupus, karamelizirani luk, bijeli umak, luk', price: '15.60', signature: true },
      { hr: 'Fishburger', en: 'Fishburger', desc: 'Brioche bun, hake fish and shrimps, lettuce, tomato, Thousand Island sauce', descHr: 'Brioche pecivo, oslić i kozice, zelena salata, rajčica, umak Thousand Island', price: '15.60' },
    ],
  },
  {
    id: 'gyros',
    hr: 'Gyros i tortilje',
    en: 'Gyros & Tortillas',
    note: 'Wrapped and ready.',
    noteHr: 'Zamotano i spremno.',
    items: [
      { hr: 'Gyros piletina', en: 'Chicken Gyros', desc: 'Chicken, bun, lettuce, cabbage, tomato, onion, sour cream, soya sauce', descHr: 'Piletina, lepinja, zelena salata, kupus, rajčica, luk, kiselo vrhnje, soya sos', price: '11.90' },
      { hr: 'Našgyros', en: 'Našgyros', desc: 'Chicken, bun, lettuce, cabbage, tomato, onion, Thousand Island sauce', descHr: 'Piletina, lepinja, zelena salata, kupus, rajčica, luk, umak Thousand Island', price: '12.90', signature: true },
      { hr: 'Tortilja piletina', en: 'Chicken Tortilla', desc: 'Chicken, tomato, cream, BBQ sauce, green salad', descHr: 'Piletina, rajčica, vrhnje, BBQ umak, zelena salata', price: '11.80' },
      { hr: 'Tortilja Sub Gourmet', en: 'Sub Gourmet Tortilla', desc: 'Chicken, green salad, tartar sauce, bacon, tomato, reduced aceto', descHr: 'Piletina, zelena salata, tartar umak, panceta, rajčica, reducirani aceto', price: '13.90', signature: true },
      { hr: 'Tortilja Vegetariana', en: 'Vegetarian Tortilla', desc: 'BBQ sauce, lettuce, tomato, mixed vegetables, spices', descHr: 'BBQ umak, zelena salata, rajčica, mix povrće, začini', price: '12.60' },
      { hr: 'Tortilja Tuna', en: 'Tuna Tortilla', desc: 'Tuna, lettuce, tomato, pickles, corn, tartar sauce', descHr: 'Tuna, zelena salata, rajčica, kiseli krastavac, kukuruz, tartar umak', price: '13.90' },
    ],
  },
  {
    id: 'kids',
    hr: 'Kutak za djecu',
    en: "Children's Corner",
    note: 'Smaller plates for smaller guests.',
    noteHr: 'Manji tanjuri za manje goste.',
    items: [
      { hr: 'Pasta Napolitana', en: 'Napolitan Pasta', desc: 'Tomato sauce, pasta', descHr: 'Umak od rajčice, pasta', price: '12.20' },
      { hr: 'Pileći banditosi', en: 'Chicken Banditos', desc: 'Fried chicken, ketchup, French fries', descHr: 'Pohana piletina, kečap, pomfrit', price: '12.30' },
    ],
  },
  {
    id: 'sides',
    hr: 'Prilozi i dodaci',
    en: 'Sides & Extras',
    note: 'Add to any plate.',
    noteHr: 'Uz svako jelo.',
    items: [
      { hr: 'Mediteransko povrće sa žara', en: 'Grilled Mediterranean Vegetables', price: '5.90' },
      { hr: 'Pomfrit', en: 'French Fries', price: '3.80' },
      { hr: 'Majoneza', en: 'Mayonnaise', price: '2.20' },
      { hr: 'Ketchup', en: 'Ketchup', price: '2.20' },
      { hr: 'Senf', en: 'Mustard', price: '2.20' },
      { hr: 'Tartar umak', en: 'Tartar Sauce', price: '2.20' },
      { hr: 'Ajvar', en: 'Ajvar', price: '2.20' },
      { hr: 'Kulen', en: 'Kulen', price: '2.20' },
      { hr: 'Panceta', en: 'Bacon', price: '2.20' },
      { hr: 'Gljive', en: 'Mushrooms', price: '2.20' },
      { hr: 'Vrhnje', en: 'Cream', price: '2.20' },
      { hr: 'Lepinja', en: 'Flat Bread', price: '2.60' },
      { hr: 'Lepinja 1/2', en: 'Flat Bread 1/2', price: '1.30' },
    ],
  },
  {
    id: 'desserts',
    hr: 'Deserti',
    en: 'Desserts',
    note: 'Home made.',
    noteHr: 'Domaće.',
    items: [
      { hr: 'Sladoled bourbon vanilija s bučinim uljem', en: 'Bourbon Vanilla Ice Cream with Pumpkin Seed Oil', price: '5.90' },
      { hr: 'Sladoled (kuglica)', en: 'Ice Cream (scoop)', price: '2.90' },
      { hr: 'Palačinke s marmeladom / čokoladom', en: 'Pancakes with Marmalade / Chocolate', price: '5.70' },
      { hr: 'Lava Cake', en: 'Lava Cake', price: '7.60' },
      { hr: 'Torta od mjendula', en: 'Almond Cake', price: '5.60' },
      { hr: 'Torta Monte', en: 'Monte Cake', price: '5.60' },
      { hr: 'Čoko-lješnjak torta', en: 'Chocolate-Hazelnut Cake', price: '5.60' },
      { hr: 'Cheesecake', en: 'Cheesecake', price: '5.60' },
    ],
  },
];

// Also read under Node when tools/prerender.js renders the pages.
(typeof window !== 'undefined' ? window : globalThis).MENU_DATA = MENU_DATA;
