const MENU_DATA = [
  {
    id: 'breakfast',
    hr: 'Doručak',
    en: 'Breakfast',
    hours: '09:00 – 11:30 · Monday to Sunday',
    note: 'Served slow, the Mediterranean way.',
    items: [
      { hr: 'Sub Gourmet doručak', en: 'Sub Gourmet Breakfast', desc: 'Fried eggs, prosciutto, paški cheese, tomato, olives, fresh bread', price: '12.90', signature: true },
      { hr: 'Omlet sa šunkom i sirom', en: 'Ham & Cheese Omelette', desc: 'Three eggs, smoked ham, edamer, chives, sourdough toast', price: '8.40' },
      { hr: 'Omlet od povrća', en: 'Garden Omelette', desc: 'Spinach, peppers, tomato, feta, parsley', price: '7.90' },
      { hr: 'Granola s jogurtom', en: 'Granola & Yoghurt', desc: 'House granola, Greek yoghurt, seasonal fruit, lavender honey', price: '6.80' },
      { hr: 'Avokado tost', en: 'Avocado Toast', desc: 'Sourdough, smashed avocado, poached egg, chili oil', price: '9.20' },
      { hr: 'Palačinke', en: 'Pancakes', desc: 'Maple, fresh berries, mascarpone', price: '7.40' },
    ],
  },
  {
    id: 'appetizers',
    hr: 'Predjela',
    en: 'Appetizers',
    note: 'To begin slowly, with bread and good company.',
    items: [
      { hr: 'Dalmatinski pršut', en: 'Dalmatian Prosciutto', desc: 'Aged 18 months, paški cheese, capers, olives', price: '14.50' },
      { hr: 'Carpaccio od goveđeg filea', en: 'Beef Tenderloin Carpaccio', desc: 'Rocket, parmesan shavings, lemon, truffle oil', price: '13.80' },
      { hr: 'Tuna tartar', en: 'Tuna Tartare', desc: 'Adriatic tuna, avocado, lime, sesame, soy reduction', price: '15.20' },
      { hr: 'Bruschette al pomodoro', en: 'Tomato Bruschetta', desc: 'Heirloom tomato, basil, olive oil, garlic', price: '7.80' },
      { hr: 'Rižoto od škampa', en: 'Shrimp Risotto', desc: 'Adriatic shrimp, white wine, cherry tomato', price: '13.40' },
    ],
  },
  {
    id: 'soups',
    hr: 'Juhe i salate',
    en: 'Soups & Salads',
    note: 'From the garden, the sea, and the soup pot.',
    items: [
      { hr: 'Riblja juha', en: 'Adriatic Fish Soup', desc: 'White fish, tomato, white wine, croutons', price: '8.90' },
      { hr: 'Goveđa juha', en: 'Beef Broth', desc: 'Slow-cooked, fine noodles, parsley', price: '5.40' },
      { hr: 'Cezar salata', en: 'Caesar Salad', desc: 'Romaine, grilled chicken, anchovy dressing, parmesan', price: '11.80' },
      { hr: 'Mediteranska salata', en: 'Mediterranean Salad', desc: 'Tomato, cucumber, feta, kalamata olives, oregano', price: '10.20' },
      { hr: 'Salata s tunom', en: 'Tuna Salad', desc: 'Mixed greens, seared tuna, capers, soft egg', price: '13.40' },
    ],
  },
  {
    id: 'pasta',
    hr: 'Tjestenina',
    en: 'Pasta',
    note: 'Hand-rolled, sauced with patience.',
    items: [
      { hr: 'Tagliatelle s umakom od tartufa', en: 'Tagliatelle with Truffle Sauce', desc: 'Fresh tagliatelle, Istrian black truffle, butter, parmesan', price: '15.30', signature: true },
      { hr: 'Spaghetti vongole', en: 'Spaghetti Vongole', desc: 'Adriatic clams, white wine, garlic, parsley', price: '16.80' },
      { hr: 'Lasagne bolognese', en: 'Lasagne Bolognese', desc: 'Layered with slow ragù and besciamella', price: '12.40' },
      { hr: 'Gnocchi quattro formaggi', en: 'Four-Cheese Gnocchi', desc: 'Gorgonzola, parmesan, mozzarella, ricotta', price: '13.20' },
      { hr: 'Penne arrabbiata', en: 'Penne Arrabbiata', desc: 'San Marzano tomato, garlic, chili, basil', price: '10.60' },
      { hr: 'Ravioli s ricottom', en: 'Ricotta Ravioli', desc: 'Brown butter, sage, walnut crumble', price: '13.80' },
    ],
  },
  {
    id: 'mains',
    hr: 'Glavna jela',
    en: 'Main Courses',
    note: 'From land and the sea two minutes away.',
    items: [
      { hr: 'Lignje na žaru', en: 'Grilled Squids', desc: 'Charcoal grilled, blitva, boiled potato, lemon', price: '19.60', signature: true },
      { hr: 'Brancin na žaru', en: 'Grilled Sea Bass', desc: 'Whole fish, olive oil, herbs, grilled vegetables', price: '24.80' },
      { hr: 'Biftek na žaru', en: 'Grilled Beef Tenderloin', desc: '220 g, peppercorn or gorgonzola sauce, baked potato', price: '28.40' },
      { hr: 'Pileći file', en: 'Chicken Fillet', desc: 'Pan-seared, lemon-thyme jus, seasonal vegetables', price: '13.90' },
      { hr: 'Janjetina ispod peke', en: 'Lamb Under the Bell', desc: 'Slow-roasted, potato, rosemary — order 24 h ahead', price: '32.00' },
      { hr: 'Pljeskavica', en: 'Balkan Pljeskavica', desc: 'Grilled beef-pork patty, ajvar, kajmak, fresh bread', price: '12.80' },
    ],
  },
  {
    id: 'pizza',
    hr: 'Pizza',
    en: 'Pizza',
    note: 'Stone oven. Three-day dough.',
    items: [
      { hr: 'Sub Gourmet Pizza', en: 'Sub Gourmet Pizza', desc: 'Prosciutto, rocket, cherry tomato, parmesan, truffle oil', price: '17.20', signature: true },
      { hr: 'Margherita', en: 'Margherita', desc: 'San Marzano tomato, fior di latte, basil', price: '9.40' },
      { hr: 'Quattro Formaggi', en: 'Four Cheese', desc: 'Mozzarella, gorgonzola, parmesan, smoked scamorza', price: '12.80' },
      { hr: 'Diavola', en: 'Diavola', desc: 'Spicy salami, chili, mozzarella, tomato', price: '11.60' },
      { hr: 'Capricciosa', en: 'Capricciosa', desc: 'Ham, mushroom, artichoke, olives, mozzarella', price: '12.20' },
      { hr: 'Vegetariana', en: 'Vegetarian', desc: 'Grilled zucchini, peppers, eggplant, ricotta', price: '11.80' },
    ],
  },
  {
    id: 'burgers',
    hr: 'Burgeri',
    en: 'Burgers',
    note: 'Brioche bun, Adriatic salt, no shortcuts.',
    items: [
      { hr: 'Sub Gourmet Burger', en: 'Sub Gourmet Burger', desc: '200 g beef, cheddar, bacon, caramelised onion, house sauce', price: '14.80', signature: true },
      { hr: 'Klasik burger', en: 'Classic Burger', desc: 'Beef, cheddar, lettuce, tomato, pickle, mustard mayo', price: '11.40' },
      { hr: 'Pileći burger', en: 'Crispy Chicken Burger', desc: 'Buttermilk chicken, slaw, chipotle aioli, brioche', price: '11.80' },
      { hr: 'Vege burger', en: 'Vegetarian Burger', desc: 'Black bean & beet patty, smoked cheese, avocado', price: '11.20' },
    ],
  },
  {
    id: 'gyros',
    hr: 'Giros i tortilje',
    en: 'Gyros & Tortillas',
    note: 'Wrapped, charred, ready to walk.',
    items: [
      { hr: 'Pileći giros', en: 'Chicken Gyros', desc: 'Marinated chicken, tzatziki, tomato, onion, fries inside', price: '9.80' },
      { hr: 'Giros tortilja', en: 'Gyros Tortilla', desc: 'Pork or chicken, ajvar, kajmak, salad, soft tortilla', price: '9.40' },
      { hr: 'Falafel tortilja', en: 'Falafel Tortilla', desc: 'House falafel, hummus, pickled cabbage, tahini', price: '8.60' },
      { hr: 'Tortilja s tunom', en: 'Tuna Tortilla', desc: 'Tuna, capers, lettuce, lemon mayo, tomato', price: '8.40' },
    ],
  },
  {
    id: 'kids',
    hr: 'Dječji kutak',
    en: "Kids' Corner",
    note: 'For the small captains of the Adriatic.',
    items: [
      { hr: 'Pileći medaljoni s pomfritom', en: 'Chicken Strips & Fries', desc: 'Crispy chicken, fries, ketchup', price: '7.80' },
      { hr: 'Mini margherita', en: 'Mini Margherita', desc: 'Small classic margherita pizza', price: '6.40' },
      { hr: 'Pasta s rajčicom', en: 'Tomato Pasta', desc: 'Penne, tomato sauce, parmesan', price: '5.80' },
      { hr: 'Mini burger s pomfritom', en: 'Mini Burger & Fries', desc: 'Small beef burger, cheddar, fries', price: '7.20' },
    ],
  },
  {
    id: 'desserts',
    hr: 'Desert',
    en: 'Desserts',
    note: 'Always room. Ask for the spoon.',
    items: [
      { hr: 'Tiramisu', en: 'Tiramisu', desc: 'Mascarpone, espresso, savoiardi, cocoa', price: '6.80' },
      { hr: 'Panna cotta', en: 'Panna Cotta', desc: 'Vanilla cream, raspberry coulis, mint', price: '6.40' },
      { hr: 'Rožata', en: 'Dubrovnik Rožata', desc: 'Caramel custard with rose liqueur — Dalmatian classic', price: '6.20' },
      { hr: 'Čokoladni soufflé', en: 'Chocolate Soufflé', desc: 'Warm dark chocolate, vanilla ice cream', price: '7.40' },
      { hr: 'Sladoled', en: 'Ice Cream Selection', desc: 'Three scoops, house-made daily', price: '5.20' },
    ],
  },
];

window.MENU_DATA = MENU_DATA;
